  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=vifa
        - POSTGRES_USER=vifa
        - POSTGRES_PASSWORD=vifa
    web:
      build: .
      restart: always
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/VFIA
      ports:
        - "8000:8000"
      depends_on:
        - db
